from app.routers import productos
from app.routers import categorias
from app.routers import proveedores
from app.routers import almacenes
from app.routers import inventario
from app.routers import pedidos
from app.routers import movimientos
from app.routers import ajustes
from app.routers import reportes
from app.routers import autenticacion